version: "2.0"

volumes:
  node-modules-evio_open_charger_map:

networks:
  evio_network:

services:
  open-charger-map:
    image: open-charger-map
    container_name: open-charger-map
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Open_Charger_Map_Microservice/:/usr/src/app
      - node-modules-evio_open_charger_map:/usr/src/app/node_modules
    networks:
      - evio_network
    restart: always
    build: "./"
    environment:
      - NODE_ENV=development
    ports:
      - 3021:3021
    command: npm run start
