version: "3.2"

networks:
  evio_network:

services:
  configs:
    image: configs
    container_name: configs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Configs_Microservice/:/usr/src/app
    networks:
      - evio_network
    restart: always
    build:
      context: ../
      dockerfile: evio_Configs_Microservice/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3028:3028
    command: npm run start
