version: "3.2"

volumes:
  node-modules-evio-questions:
  logs-volume:

networks:
  evio_network:

services:
  questions_filebeat_sidecar:
    image: docker.elastic.co/beats/filebeat:7.7.0
    container_name: questions_filebeat_sidecar
    command: filebeat -e -strict.perms=false
    networks:
      - evio_network
    volumes:
      - ./filebeat/config-dev.yml:/usr/share/filebeat/filebeat.yml
      - type: volume
        source: logs-volume
        target: /var/log/service
    environment:
      - LOGSTASH_HOSTS=http://logstash:9600
  questions:
    image: questions
    volumes:
      - type: volume
        source: logs-volume
        target: /usr/src/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Questions_Microservice:/usr/src/app
      - node-modules-evio-questions:/usr/src/app/node_modules
    container_name: questions
    networks:
      - evio_network
    restart: always
    build:
      context: ../
      dockerfile: evio_Questions_Microservice/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3013:3013
    command: npm run start
