---- Insert statuses
INSERT INTO statuses (id, code, key, description, applies_to, is_final) VALUES
(1,  '20', 'created', 'Invoice or credit note record created', 'invoice', false),
-- generate_excel
(2,  '25', 'document_excel_generated', 'Excel generated with session or credit note details', 'invoice', false),
(3,  '26', 'document_excel_generation_failed', 'Error during Excel generation', 'invoice', false),
-- send_invoice_to_phc
(4,  '30', 'send_to_third_party_error', 'Error while sending invoice/credit note to PHC', 'invoice', false),
(5,  '40', 'sent_to_third_party_successful', 'Invoice/credit note created at PHC', 'invoice', true),
-- get_invoice_creditnote_pdf
(6,  '41', 'get_invoice_creditnote_pdf_successful', 'Successfully fetched invoice or credit note PDF from PHC', 'invoice', false),
(7,  '42', 'get_invoice_creditnote_pdf_failed', 'Failed to fetch invoice or credit note PDF from PHC', 'invoice', false),
-- generate_summary_pdf
(8,  '43', 'generate_summary_pdf', 'Generated summary PDF', 'invoice', false),
(9,  '44', 'generate_summary_pdf_failed', 'Failed to generate summary PDF', 'invoice', false),
-- send_invoice_email
(10, '45', 'email_sent', 'Customer received email', 'invoice', true),
(11, '46', 'email_error', 'Failure to send email', 'invoice', false),
-- cancelInvoice
(12, '80', 'cancelled', 'No further processing', 'invoice', true);

---- Insert excel_templates
INSERT INTO excel_templates (
    id,
    template_name,
    version,
    description,
    language,
    is_active,
    template_json,
    created_at,
    updated_at
)
VALUES (
    1,
    'Detailed Session Report for B2B',
    1,
    'Complete template with detailed fields for exporting sessions to B2B customers',
    'PT',
    TRUE,
    '{
      "columns": [
        { "header": "Data de início", "key": "startDate", "width": 20 },
        { "header": "Data de fim", "key": "stopDate", "width": 20 },
        { "header": "Rede", "key": "network", "width": 20 },
        { "header": "Posto de Carregamento", "key": "hwId", "width": 30 },
        { "header": "Cidade", "key": "city", "width": 20 },
        { "header": "Duração (min)", "key": "durationMin", "width": 18 },
        { "header": "Energia total", "key": "totalPower", "width": 20 },
        { "header": "Duração do carregamento (min)", "key": "realTimeCharging", "width": 30 },
        { "header": "Potência média de carregamento (kW)", "key": "averagePower", "width": 35 },
        { "header": "CO2 emitido", "key": "CO2emitted", "width": 18 },
        { "header": "Total excl. IVA (€)", "key": "total_exc_vat", "width": 22 },
        { "header": "Taxa de IVA (%)", "key": "vat", "width": 20 },
        { "header": "Total incl. IVA (€)", "key": "total_inc_vat", "width": 22 },
        { "header": "Frota", "key": "fleetName", "width": 15 },
        { "header": "Matricula", "key": "licensePlate", "width": 20 },
        { "header": "Grupo", "key": "groupName", "width": 15 },
        { "header": "Utilizador", "key": "userIdName", "width": 25 },
        { "header": "Empresa", "key": "userIdWillPayName", "width": 20 },
        { "header": "Nº Fatura", "key": "documentNumber", "width": 20 },
        { "header": "Data de emissão", "key": "emissionDate", "width": 20 },
        { "header": "Data de vencimento", "key": "dueDate", "width": 20 },
        { "header": "Periodo de Faturação Inicio", "key": "billingPeriodStart", "width": 25 },
        { "header": "Periodo de Faturação Fim", "key": "billingPeriodEnd", "width": 25 },
        { "header": "Duração após a sessão de carregamento (min)", "key": "parkingMin", "width": 40 },
        { "header": "Taxa de activação", "key": "flatCost", "width": 22 },
        { "header": "Tarifa por kWh", "key": "unitPriceRoamingEnergy", "width": 20 },
        { "header": "Tarifa por min", "key": "unitPriceRoamingTime", "width": 20 },
        { "header": "Tarifa durante a sessão de carregamento (€/min)", "key": "chargingUseTariff", "width": 40 },
        { "header": "Tarifa após sessão de carregamento (€/min)", "key": "parkingTariff", "width": 40 },
        { "header": "Roaming Custo / Tempo €", "key": "timeCost", "width": 30 },
        { "header": "Roaming Custo / Energia €", "key": "energyCost", "width": 30 },
        { "header": "Tensão Posto", "key": "voltageLevel", "width": 20 },
        { "header": "Energia Vazio (kWh)", "key": "energyConsumedEmpty", "width": 25 },
        { "header": "Energia Fora Vazio (kWh)", "key": "energyConsumedOutEmpty", "width": 30 },
        { "header": "Total CEME MOBIE (€)", "key": "cemeTotalPrice", "width": 30 },
        { "header": "MOBIE Tarifa CEME Ativação", "key": "activationFee", "width": 30 },
        { "header": "MOBIE CEME Tarifa Vazio €/kWh", "key": "unitPriceCEMEEmptyBT", "width": 30 },
        { "header": "MOBIE CEME Tarifa Fora Vazio €/kWh", "key": "unitPriceCEMEOutEmptyBT", "width": 30 },
        { "header": "Total TAR MOBIE (€)", "key": "tar", "width": 30 },
        { "header": "MOBIE TAR Vazio MT €/kWh", "key": "unitPriceTAREmptyMT", "width": 30 },
        { "header": "MOBIE TAR Fora Vazio MT €/kWh", "key": "unitPriceTAROutEmptyMT", "width": 30 },
        { "header": "MOBIE TAR Vazio BT €/kWh", "key": "unitPriceTAREmptyBT", "width": 30 },
        { "header": "MOBIE TAR Fora Vazio BT €/kWh", "key": "unitPriceTAROutEmptyBT", "width": 30 },
        { "header": "Total OPC MOBIE (€)", "key": "opcTotalPrice", "width": 30 },
        { "header": "MOBIE OPC Tempo €/min", "key": "unitPriceOPCTime", "width": 30 },
        { "header": "MOBIE OPC Energia €/kWh", "key": "unitPriceOPCEnergy", "width": 30 },
        { "header": "MOBIE Total OPC por Tempo €", "key": "opcTimeCost", "width": 30 },
        { "header": "MOBIE Total OPC por Energia €", "key": "opcEnergyCost", "width": 30 },
        { "header": "MOBIE Total OPC Ativação €", "key": "opcFlatCost", "width": 30 },
        { "header": "Suporte à mobilidade elétrica MOBIE(€)", "key": "mobiEGrant", "width": 30 },
        { "header": "Total IEC MOBIE (€", "key": "iec", "width": 30 },
        { "header": "PartyId of OPC", "key": "partyId", "width": 30 }
      ]
    }'::jsonb,
    NOW(),
    NOW()
);

--EN
INSERT INTO excel_templates (
    id,
    template_name,
    version,
    description,
    language,
    is_active,
    template_json,
    created_at,
    updated_at
)
VALUES (
    2,
    'Detailed Session Report for B2B',
    1,
    'Complete template with detailed fields for exporting sessions to B2B customers',
    'EN',
    TRUE,
    '{
      "columns": [
        { "header": "Start Date", "key": "startDate", "width": 20 },
        { "header": "End Date", "key": "stopDate", "width": 20 },
        { "header": "Network", "key": "network", "width": 20 },
        { "header": "Charging Station", "key": "hwId", "width": 30 },
        { "header": "City", "key": "city", "width": 20 },
        { "header": "Duration (min)", "key": "durationMin", "width": 18 },
        { "header": "Total Energy", "key": "totalPower", "width": 20 },
        { "header": "Charging Duration (min)", "key": "realTimeCharging", "width": 30 },
        { "header": "Average Charging Power (kW)", "key": "averagePower", "width": 35 },
        { "header": "CO2 Emitted", "key": "CO2emitted", "width": 18 },
        { "header": "Total excl. VAT (€)", "key": "total_exc_vat", "width": 22 },
        { "header": "VAT Rate (%)", "key": "vat", "width": 20 },
        { "header": "Total incl. VAT (€)", "key": "total_inc_vat", "width": 22 },
        { "header": "Fleet", "key": "fleetName", "width": 15 },
        { "header": "License Plate", "key": "licensePlate", "width": 20 },
        { "header": "Group", "key": "groupName", "width": 15 },
        { "header": "User", "key": "userIdName", "width": 25 },
        { "header": "Company", "key": "userIdWillPayName", "width": 20 },
        { "header": "Invoice No.", "key": "documentNumber", "width": 20 },
        { "header": "Issue Date", "key": "emissionDate", "width": 20 },
        { "header": "Due Date", "key": "dueDate", "width": 20 },
        { "header": "Billing Period Start", "key": "billingPeriodStart", "width": 25 },
        { "header": "Billing Period End", "key": "billingPeriodEnd", "width": 25 },
        { "header": "Duration after charging session (min)", "key": "parkingMin", "width": 40 },
        { "header": "Activation Fee", "key": "flatCost", "width": 22 },
        { "header": "Energy Tariff (€/kWh)", "key": "unitPriceRoamingEnergy", "width": 20 },
        { "header": "Time Tariff (€/min)", "key": "unitPriceRoamingTime", "width": 20 },
        { "header": "Charging Session Tariff (€/min)", "key": "chargingUseTariff", "width": 40 },
        { "header": "Post-Session Tariff (€/min)", "key": "parkingTariff", "width": 40 },
        { "header": "Roaming Time Cost (€)", "key": "timeCost", "width": 30 },
        { "header": "Roaming Energy Cost (€)", "key": "energyCost", "width": 30 },
        { "header": "Station Voltage", "key": "voltageLevel", "width": 20 },
        { "header": "Off‑Peak Energy (kWh)", "key": "energyConsumedEmpty", "width": 25 },
        { "header": "Non‑Off‑Peak Energy (kWh)", "key": "energyConsumedOutEmpty", "width": 30 },
        { "header": "CEME MOBIE Total (€)", "key": "cemeTotalPrice", "width": 30 },
        { "header": "MOBIE CEME Activation Tariff", "key": "activationFee", "width": 30 },
        { "header": "MOBIE CEME Off‑Peak Tariff €/kWh", "key": "unitPriceCEMEEmptyBT", "width": 30 },
        { "header": "MOBIE CEME Non‑Off‑Peak Tariff €/kWh", "key": "unitPriceCEMEOutEmptyBT", "width": 30 },
        { "header": "TAR MOBIE Total (€)", "key": "tar", "width": 30 },
        { "header": "MOBIE TAR Off‑Peak MT €/kWh", "key": "unitPriceTAREmptyMT", "width": 30 },
        { "header": "MOBIE TAR Non‑Off‑Peak MT €/kWh", "key": "unitPriceTAROutEmptyMT", "width": 30 },
        { "header": "MOBIE TAR Off‑Peak BT €/kWh", "key": "unitPriceTAREmptyBT", "width": 30 },
        { "header": "MOBIE TAR Non‑Off‑Peak BT €/kWh", "key": "unitPriceTAROutEmptyBT", "width": 30 },
        { "header": "OPC MOBIE Total (€)", "key": "opcTotalPrice", "width": 30 },
        { "header": "MOBIE OPC Time €/min", "key": "unitPriceOPCTime", "width": 30 },
        { "header": "MOBIE OPC Energy €/kWh", "key": "unitPriceOPCEnergy", "width": 30 },
        { "header": "MOBIE Total OPC Time (€)", "key": "opcTimeCost", "width": 30 },
        { "header": "MOBIE Total OPC Energy (€)", "key": "opcEnergyCost", "width": 30 },
        { "header": "MOBIE Total OPC Activation (€)", "key": "opcFlatCost", "width": 30 },
        { "header": "MOBIE EV Support (€)", "key": "mobiEGrant", "width": 30 },
        { "header": "MOBIE IEC Total (€)", "key": "iec", "width": 30 },
        { "header": "OPC PartyId", "key": "partyId", "width": 30 }
      ]
    }'::jsonb,
    NOW(),
    NOW()
);
--ES
INSERT INTO excel_templates (
    id,
    template_name,
    version,
    description,
    language,
    is_active,
    template_json,
    created_at,
    updated_at
)
VALUES (
    3,
    'Informe Detallado de Sesiones para B2B',
    1,
    'Plantilla completa con campos detallados para exportar sesiones a clientes B2B',
    'ES',
    TRUE,
    '{
      "columns": [
        { "header": "Fecha de inicio", "key": "startDate", "width": 20 },
        { "header": "Fecha de fin", "key": "stopDate", "width": 20 },
        { "header": "Red", "key": "network", "width": 20 },
        { "header": "Estación de carga", "key": "hwId", "width": 30 },
        { "header": "Ciudad", "key": "city", "width": 20 },
        { "header": "Duración (min)", "key": "durationMin", "width": 18 },
        { "header": "Energía total", "key": "totalPower", "width": 20 },
        { "header": "Duración de carga (min)", "key": "realTimeCharging", "width": 30 },
        { "header": "Potencia media de carga (kW)", "key": "averagePower", "width": 35 },
        { "header": "CO2 emitido", "key": "CO2emitted", "width": 18 },
        { "header": "Total sin IVA (€)", "key": "total_exc_vat", "width": 22 },
        { "header": "Tasa de IVA (%)", "key": "vat", "width": 20 },
        { "header": "Total con IVA (€)", "key": "total_inc_vat", "width": 22 },
        { "header": "Flota", "key": "fleetName", "width": 15 },
        { "header": "Matrícula", "key": "licensePlate", "width": 20 },
        { "header": "Grupo", "key": "groupName", "width": 15 },
        { "header": "Usuario", "key": "userIdName", "width": 25 },
        { "header": "Empresa", "key": "userIdWillPayName", "width": 20 },
        { "header": "Nº Factura", "key": "documentNumber", "width": 20 },
        { "header": "Fecha de emisión", "key": "emissionDate", "width": 20 },
        { "header": "Fecha de vencimiento", "key": "dueDate", "width": 20 },
        { "header": "Inicio período de facturación", "key": "billingPeriodStart", "width": 25 },
        { "header": "Fin período de facturación", "key": "billingPeriodEnd", "width": 25 },
        { "header": "Duración tras la sesión (min)", "key": "parkingMin", "width": 40 },
        { "header": "Tasa de activación", "key": "flatCost", "width": 22 },
        { "header": "Tarifa por kWh", "key": "unitPriceRoamingEnergy", "width": 20 },
        { "header": "Tarifa por min", "key": "unitPriceRoamingTime", "width": 20 },
        { "header": "Tarifa durante la sesión (€/min)", "key": "chargingUseTariff", "width": 40 },
        { "header": "Tarifa tras la sesión (€/min)", "key": "parkingTariff", "width": 40 },
        { "header": "Roaming Costo / Tiempo €", "key": "timeCost", "width": 30 },
        { "header": "Roaming Costo / Energía €", "key": "energyCost", "width": 30 },
        { "header": "Voltaje de estación", "key": "voltageLevel", "width": 20 },
        { "header": "Energía Valle (kWh)", "key": "energyConsumedEmpty", "width": 25 },
        { "header": "Energía Fuera de Valle (kWh)", "key": "energyConsumedOutEmpty", "width": 30 },
        { "header": "Total CEME MOBIE (€)", "key": "cemeTotalPrice", "width": 30 },
        { "header": "Tarifa activación CEME MOBIE", "key": "activationFee", "width": 30 },
        { "header": "Tarifa CEME Valle €/kWh", "key": "unitPriceCEMEEmptyBT", "width": 30 },
        { "header": "Tarifa CEME Fuera de Valle €/kWh", "key": "unitPriceCEMEOutEmptyBT", "width": 30 },
        { "header": "Total TAR MOBIE (€)", "key": "tar", "width": 30 },
        { "header": "TAR Valle MT €/kWh", "key": "unitPriceTAREmptyMT", "width": 30 },
        { "header": "TAR Fuera de Valle MT €/kWh", "key": "unitPriceTAROutEmptyMT", "width": 30 },
        { "header": "TAR Valle BT €/kWh", "key": "unitPriceTAREmptyBT", "width": 30 },
        { "header": "TAR Fuera de Valle BT €/kWh", "key": "unitPriceTAROutEmptyBT", "width": 30 },
        { "header": "Total OPC MOBIE (€)", "key": "opcTotalPrice", "width": 30 },
        { "header": "OPC Tiempo €/min", "key": "unitPriceOPCTime", "width": 30 },
        { "header": "OPC Energía €/kWh", "key": "unitPriceOPCEnergy", "width": 30 },
        { "header": "Total Tiempo OPC (€)", "key": "opcTimeCost", "width": 30 },
        { "header": "Total Energía OPC (€)", "key": "opcEnergyCost", "width": 30 },
        { "header": "Total Activación OPC (€)", "key": "opcFlatCost", "width": 30 },
        { "header": "Apoyo movilidad eléctrica MOBIE (€)", "key": "mobiEGrant", "width": 30 },
        { "header": "Total IEC MOBIE (€)", "key": "iec", "width": 30 },
        { "header": "PartyId de OPC", "key": "partyId", "width": 30 }
      ]
    }'::jsonb,
    NOW(),
    NOW()
);

--FR
INSERT INTO excel_templates (
    id,
    template_name,
    version,
    description,
    language,
    is_active,
    template_json,
    created_at,
    updated_at
)
VALUES (
    4,
    'Rapport Détaillé des Sessions pour B2B',
    1,
    'Modèle complet avec champs détaillés pour exporter les sessions aux clients B2B',
    'FR',
    TRUE,
    '{
      "columns": [
        { "header": "Date de début", "key": "startDate", "width": 20 },
        { "header": "Date de fin", "key": "stopDate", "width": 20 },
        { "header": "Réseau", "key": "network", "width": 20 },
        { "header": "Station de recharge", "key": "hwId", "width": 30 },
        { "header": "Ville", "key": "city", "width": 20 },
        { "header": "Durée (min)", "key": "durationMin", "width": 18 },
        { "header": "Énergie totale", "key": "totalPower", "width": 20 },
        { "header": "Durée de charge (min)", "key": "realTimeCharging", "width": 30 },
        { "header": "Puissance moyenne de charge (kW)", "key": "averagePower", "width": 35 },
        { "header": "CO2 émis", "key": "CO2emitted", "width": 18 },
        { "header": "Total HT (€)", "key": "total_exc_vat", "width": 22 },
        { "header": "Taux de TVA (%)", "key": "vat", "width": 20 },
        { "header": "Total TTC (€)", "key": "total_inc_vat", "width": 22 },
        { "header": "Flotte", "key": "fleetName", "width": 15 },
        { "header": "Plaque d’immatriculation", "key": "licensePlate", "width": 20 },
        { "header": "Groupe", "key": "groupName", "width": 15 },
        { "header": "Utilisateur", "key": "userIdName", "width": 25 },
        { "header": "Entreprise", "key": "userIdWillPayName", "width": 20 },
        { "header": "N° Facture", "key": "documentNumber", "width": 20 },
        { "header": "Date d’émission", "key": "emissionDate", "width": 20 },
        { "header": "Date d’échéance", "key": "dueDate", "width": 20 },
        { "header": "Début de facturation", "key": "billingPeriodStart", "width": 25 },
        { "header": "Fin de facturation", "key": "billingPeriodEnd", "width": 25 },
        { "header": "Durée après session (min)", "key": "parkingMin", "width": 40 },
        { "header": "Frais d’activation", "key": "flatCost", "width": 22 },
        { "header": "Tarif par kWh", "key": "unitPriceRoamingEnergy", "width": 20 },
        { "header": "Tarif par min", "key": "unitPriceRoamingTime", "width": 20 },
        { "header": "Tarif pendant la session (€/min)", "key": "chargingUseTariff", "width": 40 },
        { "header": "Tarif post-session (€/min)", "key": "parkingTariff", "width": 40 },
        { "header": "Coût roaming / temps €", "key": "timeCost", "width": 30 },
        { "header": "Coût roaming / énergie €", "key": "energyCost", "width": 30 },
        { "header": "Tension de la borne", "key": "voltageLevel", "width": 20 },
        { "header": "Énergie Heures Creuses (kWh)", "key": "energyConsumedEmpty", "width": 25 },
        { "header": "Énergie Hors Heures Creuses (kWh)", "key": "energyConsumedOutEmpty", "width": 30 },
        { "header": "Total CEME MOBIE (€)", "key": "cemeTotalPrice", "width": 30 },
        { "header": "Tarif activation CEME MOBIE", "key": "activationFee", "width": 30 },
        { "header": "Tarif Heures Creuses CEME €/kWh", "key": "unitPriceCEMEEmptyBT", "width": 30 },
        { "header": "Tarif Hors Heures Creuses CEME €/kWh", "key": "unitPriceCEMEOutEmptyBT", "width": 30 },
        { "header": "Total TAR MOBIE (€)", "key": "tar", "width": 30 },
        { "header": "TAR Heures Creuses MT €/kWh", "key": "unitPriceTAREmptyMT", "width": 30 },
        { "header": "TAR Hors Heures Creuses MT €/kWh", "key": "unitPriceTAROutEmptyMT", "width": 30 },
        { "header": "TAR Heures Creuses BT €/kWh", "key": "unitPriceTAREmptyBT", "width": 30 },
        { "header": "TAR Hors Heures Creuses BT €/kWh", "key": "unitPriceTAROutEmptyBT", "width": 30 },
        { "header": "Total OPC MOBIE (€)", "key": "opcTotalPrice", "width": 30 },
        { "header": "OPC Temps €/min", "key": "unitPriceOPCTime", "width": 30 },
        { "header": "OPC Énergie €/kWh", "key": "unitPriceOPCEnergy", "width": 30 },
        { "header": "Total Temps OPC (€)", "key": "opcTimeCost", "width": 30 },
        { "header": "Total Énergie OPC (€)", "key": "opcEnergyCost", "width": 30 },
        { "header": "Total Activation OPC (€)", "key": "opcFlatCost", "width": 30 },
        { "header": "Soutien mobilité électrique MOBIE (€)", "key": "mobiEGrant", "width": 30 },
        { "header": "Total IEC MOBIE (€)", "key": "iec", "width": 30 },
        { "header": "PartyId de l’OPC", "key": "partyId", "width": 30 }
      ]
    }'::jsonb,
    NOW(),
    NOW()
);

---- Insert vat_statuses
INSERT INTO vat_statuses (id, tab_iva, country, value) VALUES
(nextval('vat_statuses_id_seq'::regclass), 2, 'PT', 0.23),
(nextval('vat_statuses_id_seq'::regclass), 4, '', 0),
(nextval('vat_statuses_id_seq'::regclass), 5, 'ES', 0.21),
(nextval('vat_statuses_id_seq'::regclass), 6, 'FR', 0.20),
(nextval('vat_statuses_id_seq'::regclass), 7, 'PT', 0.22),
(nextval('vat_statuses_id_seq'::regclass), 8, 'PT', 0.16);

---- Insert invoice_layouts
INSERT INTO invoice_layouts (title, doctype, printtypeid) VALUES
('Fatura GoEvio Português', 1, 'cq16021740973,590000022'),
('Fatura GoEvio Francês', 1, 'ADM25063058062,330599011'),
('Fatura GoEvio Inglês', 1, 'ADM25063058084,309651708'),
('Fatura GoEvio Espanhol', 1, 'ADM25063058108,788371215'),
('Fatura Hyundai Português', 13, 'ADM25063072001,399938841'),
('Fatura Hyundai Espanhol', 13, 'ADM25063072107,992584631'),
('Fatura Hyundai Francês', 13, 'ADM25063072185,824610552'),
('Fatura Hyundai Inglês', 13, 'ADM25063072259,352987743'),
('Fatura ACP Português', 14, 'ADM25063070376,661490202'),
('Fatura ACP Francês', 14, 'ADM25063070429,143456166'),
('Fatura ACP Inglês', 14, 'ADM25063070445,924450583'),
('Fatura ACP Espanhol', 14, 'ADM25063070460,117341170'),
('Fatura Gocharge Português', 15, 'ADM25063071927,549209569'),
('Fatura Gocharge Inglês', 15, 'ADM25063071268,600926109'),
('Fatura Gocharge Francês', 15, 'ADM25063071280,896010163'),
('Fatura Gocharge Espanhol', 15, 'ADM25063071296,591139922');

-- Insert tax_exemptions
INSERT INTO tax_exemptions (code, description, language) VALUES
('M01', 'Artigo 16.º, n.º 6 do CIVA', 'PT'),
('M01', 'Article 16, paragraph 6 of the VAT Code', 'EN'),
('M01', 'Artículo 16, apartado 6 del Código del IVA', 'ES'),
('M01', 'Article 16, paragraphe 6 du Code de la TVA', 'FR');