apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend

resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: evio-platform
    envs:
      - env
    options:
      disableNameSuffixHash: true
