apiVersion: v1
kind: Service
metadata:
  name: ocpp15
  namespace: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0cf96f4d4eaf70a2b"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations:  "eipalloc-0f19940f6dd30a5c9"
