openapi: 3.0.0
info:
  title: EVIO APT Payments API's
  version: 1.0.0
  description: APIs for the EVIO Payments Microservice
servers:
  - url: http://localhost:3000
  

paths:
  /api/private/apt/{token}/prepayment:
    post:
      tags:
      - External
      description: |
        This endpoint will serve to create a new APT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APT'
      responses:
        '200':
          description: Successful
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
      security:
        - bearerAuth: []

  /api/private/apt/{token}/payment:
    post:
      tags:
      - External
      description: Retrieve pre-authorizations from the server.
      parameters:
        - name: apikey
          in: path
          required: true
          schema:
            type: string
            minimum: 1
          description: The apt apikey 
      responses:
        '200':
          description: Successful
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
      security:
        - bearerAuth: []
                   
  /api/private/apt/{token}/refoud:
    post:
      tags:
      - External
      description: Retrieve pre-authorizations from the server.
      parameters:
        - name: apikey
          in: path
          required: true
          schema:
            type: string
            minimum: 1
          description: The apt apikey 
      responses:
        '200':
          description: Successful
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
      security:
        - bearerAuth: []
     


components:  
  schemas:
    APT:
      type: object
      properties:
        token:
          type: string
          description: Unique reference for identify APT
        name:
          type: string
        model:
          type: string
        operactor:
          type: string
        serial_number:
          type: string
        geometry:
          type: object
          properties:
            type:
              type: string
            coordinates:
              type: array
              items:
                type: number
        address:
          type: object
          properties:
            city:
              type: string
            country:
              type: string
            countryCode:
              type: string
            number:
              type: string
            floor:
              type: string
            state:
              type: string
            street:
              type: string
            zipCode:
              type: string
        chargers:
          type: array
          items:
            type: string
      required:
        - token
        - name
        - model
        - operactor
        - serial_number
        - geometry
        - address
        - chargers
    Chargers:
      type: object
        



  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer




