apiVersion: apps/v1
kind: Deployment
metadata:
  name: oicp
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oicp
  template:
    metadata:
      labels:
        app: oicp
    spec:
      containers:
        - name: oicp
          image: image
          ports:
            - containerPort: 3102
          resources:
            limits:
              cpu: "150m"
              memory: "300Mi"
            requests:
              cpu: "90m"
              memory: "120Mi"
          args:
            - npm
            - run
            - start:prod
          envFrom:
            - configMapRef:
                name: oicp
            - configMapRef:
                name: shared-envs
            - secretRef:
                name: shared-secrets
            - secretRef:
                name: oicp-secrets
