export enum CHARGING_SESSION_STATUS {
    UNPAID = 'UNPAID',
    PAID = 'PAID',
    CANCELED = 'CANCELED',
    PAID_WAITING_EVIO = 'PAID AND EVIO CONFIRMATION WAITING',
    NOT_APPLIED = 'NA',
}

export default {
    ChargingSessionsStatusEnum: CHARGING_SESSION_STATUS,
};
