export enum CardPhysicalStateEnum {
    VIRTUALONLY = 'VIRTUALONLY',
    REQUESTEDBYCUSTOMER = 'REQUESTEDBYCUSTOMER',
    CANCELEDBYEVIO = 'CANCELEDBYEVIO',
    REQUESTEDTOTHIRDPARTY = 'REQUESTEDTOTHIRDPARTY',
    ASSOCIATED = 'ASSOCIATED',
    ACTIVE = 'ACTIVE',
    CANCELEDBYCUSTOMER = 'CANCELEDBYCUSTOMER'
}

export enum CancellationReasonEnum {
    OTHER = 'OTHER',
    LOST = 'LOST',
    THEFT = 'THEFT'
}

export enum CardPhysicalPaymentStateEnum {
    FREE = 'FREE',
    CHARGEPAYMENT = 'CHARGEPAYMENT',
    PAYMENTFAILURE = 'PAYMENTFAILURE',
    PROCESSING = 'PROCESSING',
    PAID = 'PAID'
}