export enum KnownDomains {
    GMAIL = 'gmail.com',
    HOTMAIL = 'hotmail.com',
    YAHOO = 'yahoo.com',
    AOL = 'aol.com',
    OUTLOOK = 'outlook.com',
    ICLOUD = 'icloud.com',
    LIVE = 'live.com',
    LIVE_PT = 'live.com.pt',
    MSN = 'msn.com',
    MAIL = 'mail.com',
    PROTONMAIL = 'protonmail.com',
    ZOHO = 'zoho.com',
    YANDEX = 'yandex.com',
    GMX = 'gmx.com',
    AOL_DE = 'aol.de',
    WEB_DE = 'web.de',
    NCHES_PT = 'nches.pt',
    SONAECAPIRAL = 'sonaecapital.pt'
}