version: "2.0"

volumes:
  node-modules-evio-payments:
  logs-volume:

networks:
  evio_network:

services:
  payments_filebeat_sidecar:
    image: docker.elastic.co/beats/filebeat:7.7.0
    platform: linux/amd64
    container_name: payments_filebeat_sidecar
    command: filebeat -e -strict.perms=false
    network_mode: "host"
    volumes:
      - ./filebeat/config-dev.yml:/usr/share/filebeat/filebeat.yml
      - type: volume
        source: logs-volume
        target: /var/log/service
    environment:
      - LDAP_HOST=ldap://localhost:1041
      - DB_URI=mongodb://localhost:27017
      - LOGSTASH_HOSTS=http://localhost:9600
  payments:
    image: payments
    container_name: payments
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: logs-volume
        target: /usr/src/app/logs      
    networks:
      - evio_network
    restart: always
    build:
      context: ../
      dockerfile: evio_Payments_Microservice/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3017:3017"
    command: npm run start
