version: "2.0"

volumes:
  node-modules-evio-language:

networks:
  evio_network:

services:
  language:
    image: language
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Language_Microservice:/usr/src/app
      - node-modules-evio-language:/usr/src/app/node_modules
    container_name: language
    networks:
      - evio_network
    restart: always
    build: "./"
    environment:
      - NODE_ENV=development
    ports:
      - 3005:3005
    command: npm run start
