version: "2.0"

volumes:
  node-modules-evio-tool_ocpi_22:

networks:
  evio_network:

services:
  testing-tool-ocpi-22:
    image: testing-tool-ocpi-22
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Testing_Tool_OCPI_22_Microservice:/usr/src/app
      - node-modules-evio-tool_ocpi_22:/usr/src/app/node_modules
    container_name: testing-tool-ocpi-22
    networks:
      - evio_network
    restart: always
    build: "./"
    environment:
      - NODE_ENV=development
    ports:
      - 3020:3020
    command: npm run start
