apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: backend
spec:
  template:
    spec:
      containers:
        - name: assets
          resources:
            limits:
              cpu: "450m"
              memory: "800Mi"
            requests:
              cpu: "120m"
              memory: "250Mi"
