apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oicp-secrets-provider-class
  namespace: backend
spec:
  provider: aws
  parameters:
    region: eu-west-1
    objects: |
      - objectName: "shared-secrets"
        objectType: "secretsmanager"
        jmesPath:
        - path: "OICP_SSH_CA"
          objectAlias: "SSH_CA"
        - path: "OICP_SSH_PEM"
          objectAlias: "SSH_PEM"
        - path: "OICP_SSH_KEY"
          objectAlias: "SSH_KEY"

  secretObjects: 
    - secretName: oicp-secrets
      type: Opaque
      data:
        - key: "SSH_CA"
          objectName: SSH_CA
        - key: "SSH_PEM"
          objectName: SSH_PEM
        - key: "SSH_KEY"
          objectName: SSH_KEY