name: Deploy (manual) to Dev/QA

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente de destino"
        type: choice
        options: [development, qa]   # 'development' será normalizado para 'dev'
        default: development
      services:
        description: "Serviços (all ou lista separada por vírgulas)"
        default: "all"
      diff_base:
        description: "Base para diff quando services=all"
        default: "master"

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout (branch escolhida no UI)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configurar AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Dependências (jq)
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Resolver serviços e fazer deploy
        env:
          INPUT_ENV: ${{ inputs.environment }}
          INPUT_SERVICES: ${{ inputs.services }}
          DIFF_BASE: ${{ inputs.diff_base }}
          GIT_SHA: ${{ github.sha }}
        run: |
          bash .github/scripts/resolve_and_deploy.sh
