name: Deploy (manual) to Dev/QA
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente de destino"
        type: choice
        options: [development, qa]
        required: true
        default: development
      services:
        description: "Serviços (all ou lista)"
        required: false
        default: "all"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout the selected ref from UI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}           # <- a mesma ref escolhida em "Use workflow from"
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Normalize env and trigger CD
        env:
          SERVICES: ${{ inputs.services }}
          TARGET_ENV: ${{ inputs.environment }}
        run: |
          set -e
          # normalizar 'development' -> 'dev' (se os pipelines usam 'dev')
          ENV_NORM="$TARGET_ENV"
          [[ "$ENV_NORM" == "development" ]] && ENV_NORM="dev"
          chmod +x .ci/trigger_cd.sh
          .ci/trigger_cd.sh "$ENV_NORM"
          echo "Done deploying to $ENV_NORM"
