version: "2.0"

volumes:
  node-modules-evio-tariff:

networks:
  evio_network:

services:
  tariffs:
    image: tariffs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./evio_Tariffs_Microservice:/usr/src/app
      - node-modules-evio-tariff:/usr/src/app/node_modules
    container_name: tariffs
    networks:
      - evio_network
    restart: always
    build: "./"
    environment:
      - NODE_ENV=development
    ports:
      - 3009:3009
    command: npm run start
